export const environment = {
    production: false,
    //APIUrl:  "https://localhost:44320",
    //APIUrl: 'https://portal.distone.com/ecommerceapi',
    //APIUrl:  'http://admin.brpdevelopment.com',
    //APIUrl:  "https://stagingapi.krayden.com",
    //APIUrl:  "https://admin.brpdevelopment.com/kraydenapi",
    APIUrl:  "https://admin.brpdevelopment.com/kraydenproductionapi",
    //APIUrl:  "https://admin.brpdevelopment.com/casafinaproductionapi",
    //APIUrl:  "https://admin.brpdevelopment.com/powerdriveproductionapi",
    //APIUrl:  "https://admin.brpdevelopment.com/casafinaapi",
    ////APIUrl:  "https://portal.distone.com/CLSMITHapi",
    //APIUrl:  "https://paymentportal.distone.com/kensingtonapi",
    cookname: 'kraydenproduction121423',
    storagetime: ((60000 * 1 * 60) * 12),
    isheaderbanner: 0,
    ga:'GTM-58CCZTH6',
    iskyraden:true,
    iscasafina:false,
    ispowerdrive:false,
    wanted_date:"Wanted Date",
    //wanted_date:"Customer Receive Date",
};
